### PR TITLE
Create ct-addendum.md

### PR DESCRIPTION
**Pull request by bjaxx**
A new Connecticut law requires certain provisions to be included in the contracts between us and the Districts in addition to our existing privacy policy.  This addendum is written as a standalone provision, with the intent that if asked by a district in Connecticut, a rep can point to this provision without having to explain how the language is integrated into the privacy policy.

### CODE REVIEW

**Comment by michaelglass** [comment]
do we want this addendum viewable from the webpage? If so: it'll be engineering work unless we add it to the policy doc.

**Comment by bjaxx** [comment]
We want to put this on a new page and add a link to it from /privacy.

**Comment by michaelglass** [comment]
created a story in the sweep https://www.pivotaltracker.com/story/show/145265515

**Comment by raorao** [comment]
merging this. the engineering work relies on this document being on the master branch of this repo. feel free to revert @bjaxx if necessary

**Pull request merged**
